sudo: required
services:
  - docker

before_install:
  - docker build -t relengar/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run relengar/react-test npm test -- --coverage

after_success:
  - docker build -t relengar/multi-client ./client
  - docker build -t relengar/multi-nginx ./nginx
  - docker build -t relengar/multi-server ./server
  - docker build -t relengar/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push relengar/multi-client 
  - docker push relengar/multi-nginx 
  - docker push relengar/multi-server
  - docker push relengar/multi-worker